// Regenerates lib/chain/abis/generated.ts from Foundry artifacts (contracts/out).
// Run after `forge build`: node scripts/sync-abis.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "../../contracts/out");
const target = join(here, "../lib/chain/abis/generated.ts");
const contracts = ["DecisionRegistry", "DecisionEngine", "ExecutionVault", "OutcomeRegistry"];

const lower = (s) => s[0].toLowerCase() + s.slice(1);
let src = "// Generated by scripts/sync-abis.mjs from contracts/out. Do not edit.\n\n";
for (const name of contracts) {
  const artifact = JSON.parse(readFileSync(join(out, `${name}.sol`, `${name}.json`), "utf8"));
  src += `export const ${lower(name)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
}
writeFileSync(target, src);
console.log(`wrote ${target}`);
